// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/jmoiron/sqlx"
	mock "github.com/stretchr/testify/mock"
	"github.com/wizards-0/go-pins/migrator/dao"
	"github.com/wizards-0/go-pins/migrator/types"
)

// NewMockMigrationDao creates a new instance of MockMigrationDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMigrationDao(orig dao.MigrationDao, t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMigrationDao {
	mock := &MockMigrationDao{orig: orig}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMigrationDao is an autogenerated mock type for the MigrationDao type
type MockMigrationDao struct {
	mock.Mock
	orig dao.MigrationDao
}

type MockMigrationDao_Expecter struct {
	mock *mock.Mock
}

var passThroughMap = map[string]func(_mock *MockMigrationDao){

	"DeleteMigrationLog": func(mockMigrationDao *MockMigrationDao) {
		mockMigrationDao.EXPECT().DeleteMigrationLog(
			mock.Anything,
			mock.Anything,
		).RunAndReturn(func(tx *sqlx.Tx, mLog types.MigrationLog) (err error) {
			return mockMigrationDao.orig.DeleteMigrationLog(tx, mLog)
		}).Once()
	},
	"ExecuteQuery": func(mockMigrationDao *MockMigrationDao) {
		mockMigrationDao.EXPECT().ExecuteQuery(
			mock.Anything,
			mock.Anything,
		).RunAndReturn(func(tx *sqlx.Tx, m types.Migration) (err error) {
			return mockMigrationDao.orig.ExecuteQuery(tx, m)
		}).Once()
	},
	"ExecuteRollback": func(mockMigrationDao *MockMigrationDao) {
		mockMigrationDao.EXPECT().ExecuteRollback(
			mock.Anything,
			mock.Anything,
		).RunAndReturn(func(tx *sqlx.Tx, m types.Migration) (err error) {
			return mockMigrationDao.orig.ExecuteRollback(tx, m)
		}).Once()
	},
	"GetMigrationLogs": func(mockMigrationDao *MockMigrationDao) {
		mockMigrationDao.EXPECT().GetMigrationLogs(
			mock.Anything,
		).RunAndReturn(func(tx *sqlx.Tx) (migrationLogs []types.MigrationLog, err error) {
			return mockMigrationDao.orig.GetMigrationLogs(tx)
		}).Once()
	},
	"InsertMigrationLog": func(mockMigrationDao *MockMigrationDao) {
		mockMigrationDao.EXPECT().InsertMigrationLog(
			mock.Anything,
			mock.Anything,
		).RunAndReturn(func(tx *sqlx.Tx, mLog types.MigrationLog) (err error) {
			return mockMigrationDao.orig.InsertMigrationLog(tx, mLog)
		}).Once()
	},
	"SetupMigrationTable": func(mockMigrationDao *MockMigrationDao) {
		mockMigrationDao.EXPECT().SetupMigrationTable(
			mock.Anything,
		).RunAndReturn(func(tx *sqlx.Tx) (err error) {
			return mockMigrationDao.orig.SetupMigrationTable(tx)
		}).Once()
	},
}

func (_mock *MockMigrationDao) PassThrough(methodNames ...string) {
	for _, name := range methodNames {
		fn, exists := passThroughMap[name]
		if exists {
			fn(_mock)
		}
	}
}

func (_m *MockMigrationDao) EXPECT() *MockMigrationDao_Expecter {
	return &MockMigrationDao_Expecter{mock: &_m.Mock}
}

// DeleteMigrationLog provides a mock function for the type MockMigrationDao
func (_mock *MockMigrationDao) DeleteMigrationLog(tx *sqlx.Tx, mLog types.MigrationLog) error {
	ret := _mock.Called(tx, mLog)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMigrationLog")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*sqlx.Tx, types.MigrationLog) error); ok {
		r0 = returnFunc(tx, mLog)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMigrationDao_DeleteMigrationLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMigrationLog'
type MockMigrationDao_DeleteMigrationLog_Call struct {
	*mock.Call
}

// DeleteMigrationLog is a helper method to define mock.On call
//   - tx *sqlx.Tx
//   - mLog types.MigrationLog
func (_e *MockMigrationDao_Expecter) DeleteMigrationLog(tx interface{}, mLog interface{}) *MockMigrationDao_DeleteMigrationLog_Call {
	return &MockMigrationDao_DeleteMigrationLog_Call{Call: _e.mock.On("DeleteMigrationLog", tx, mLog)}
}

func (_c *MockMigrationDao_DeleteMigrationLog_Call) Run(run func(tx *sqlx.Tx, mLog types.MigrationLog)) *MockMigrationDao_DeleteMigrationLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *sqlx.Tx
		if args[0] != nil {
			arg0 = args[0].(*sqlx.Tx)
		}
		var arg1 types.MigrationLog
		if args[1] != nil {
			arg1 = args[1].(types.MigrationLog)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMigrationDao_DeleteMigrationLog_Call) Return(err error) *MockMigrationDao_DeleteMigrationLog_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMigrationDao_DeleteMigrationLog_Call) RunAndReturn(run func(tx *sqlx.Tx, mLog types.MigrationLog) error) *MockMigrationDao_DeleteMigrationLog_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteQuery provides a mock function for the type MockMigrationDao
func (_mock *MockMigrationDao) ExecuteQuery(tx *sqlx.Tx, m types.Migration) error {
	ret := _mock.Called(tx, m)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteQuery")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*sqlx.Tx, types.Migration) error); ok {
		r0 = returnFunc(tx, m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMigrationDao_ExecuteQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteQuery'
type MockMigrationDao_ExecuteQuery_Call struct {
	*mock.Call
}

// ExecuteQuery is a helper method to define mock.On call
//   - tx *sqlx.Tx
//   - m types.Migration
func (_e *MockMigrationDao_Expecter) ExecuteQuery(tx interface{}, m interface{}) *MockMigrationDao_ExecuteQuery_Call {
	return &MockMigrationDao_ExecuteQuery_Call{Call: _e.mock.On("ExecuteQuery", tx, m)}
}

func (_c *MockMigrationDao_ExecuteQuery_Call) Run(run func(tx *sqlx.Tx, m types.Migration)) *MockMigrationDao_ExecuteQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *sqlx.Tx
		if args[0] != nil {
			arg0 = args[0].(*sqlx.Tx)
		}
		var arg1 types.Migration
		if args[1] != nil {
			arg1 = args[1].(types.Migration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMigrationDao_ExecuteQuery_Call) Return(err error) *MockMigrationDao_ExecuteQuery_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMigrationDao_ExecuteQuery_Call) RunAndReturn(run func(tx *sqlx.Tx, m types.Migration) error) *MockMigrationDao_ExecuteQuery_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteRollback provides a mock function for the type MockMigrationDao
func (_mock *MockMigrationDao) ExecuteRollback(tx *sqlx.Tx, m types.Migration) error {
	ret := _mock.Called(tx, m)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteRollback")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*sqlx.Tx, types.Migration) error); ok {
		r0 = returnFunc(tx, m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMigrationDao_ExecuteRollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteRollback'
type MockMigrationDao_ExecuteRollback_Call struct {
	*mock.Call
}

// ExecuteRollback is a helper method to define mock.On call
//   - tx *sqlx.Tx
//   - m types.Migration
func (_e *MockMigrationDao_Expecter) ExecuteRollback(tx interface{}, m interface{}) *MockMigrationDao_ExecuteRollback_Call {
	return &MockMigrationDao_ExecuteRollback_Call{Call: _e.mock.On("ExecuteRollback", tx, m)}
}

func (_c *MockMigrationDao_ExecuteRollback_Call) Run(run func(tx *sqlx.Tx, m types.Migration)) *MockMigrationDao_ExecuteRollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *sqlx.Tx
		if args[0] != nil {
			arg0 = args[0].(*sqlx.Tx)
		}
		var arg1 types.Migration
		if args[1] != nil {
			arg1 = args[1].(types.Migration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMigrationDao_ExecuteRollback_Call) Return(err error) *MockMigrationDao_ExecuteRollback_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMigrationDao_ExecuteRollback_Call) RunAndReturn(run func(tx *sqlx.Tx, m types.Migration) error) *MockMigrationDao_ExecuteRollback_Call {
	_c.Call.Return(run)
	return _c
}

// GetMigrationLogs provides a mock function for the type MockMigrationDao
func (_mock *MockMigrationDao) GetMigrationLogs(tx *sqlx.Tx) ([]types.MigrationLog, error) {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for GetMigrationLogs")
	}

	var r0 []types.MigrationLog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*sqlx.Tx) ([]types.MigrationLog, error)); ok {
		return returnFunc(tx)
	}
	if returnFunc, ok := ret.Get(0).(func(*sqlx.Tx) []types.MigrationLog); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.MigrationLog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*sqlx.Tx) error); ok {
		r1 = returnFunc(tx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMigrationDao_GetMigrationLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMigrationLogs'
type MockMigrationDao_GetMigrationLogs_Call struct {
	*mock.Call
}

// GetMigrationLogs is a helper method to define mock.On call
//   - tx *sqlx.Tx
func (_e *MockMigrationDao_Expecter) GetMigrationLogs(tx interface{}) *MockMigrationDao_GetMigrationLogs_Call {
	return &MockMigrationDao_GetMigrationLogs_Call{Call: _e.mock.On("GetMigrationLogs", tx)}
}

func (_c *MockMigrationDao_GetMigrationLogs_Call) Run(run func(tx *sqlx.Tx)) *MockMigrationDao_GetMigrationLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *sqlx.Tx
		if args[0] != nil {
			arg0 = args[0].(*sqlx.Tx)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMigrationDao_GetMigrationLogs_Call) Return(migrationLogs []types.MigrationLog, err error) *MockMigrationDao_GetMigrationLogs_Call {
	_c.Call.Return(migrationLogs, err)
	return _c
}

func (_c *MockMigrationDao_GetMigrationLogs_Call) RunAndReturn(run func(tx *sqlx.Tx) ([]types.MigrationLog, error)) *MockMigrationDao_GetMigrationLogs_Call {
	_c.Call.Return(run)
	return _c
}

// InsertMigrationLog provides a mock function for the type MockMigrationDao
func (_mock *MockMigrationDao) InsertMigrationLog(tx *sqlx.Tx, mLog types.MigrationLog) error {
	ret := _mock.Called(tx, mLog)

	if len(ret) == 0 {
		panic("no return value specified for InsertMigrationLog")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*sqlx.Tx, types.MigrationLog) error); ok {
		r0 = returnFunc(tx, mLog)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMigrationDao_InsertMigrationLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertMigrationLog'
type MockMigrationDao_InsertMigrationLog_Call struct {
	*mock.Call
}

// InsertMigrationLog is a helper method to define mock.On call
//   - tx *sqlx.Tx
//   - mLog types.MigrationLog
func (_e *MockMigrationDao_Expecter) InsertMigrationLog(tx interface{}, mLog interface{}) *MockMigrationDao_InsertMigrationLog_Call {
	return &MockMigrationDao_InsertMigrationLog_Call{Call: _e.mock.On("InsertMigrationLog", tx, mLog)}
}

func (_c *MockMigrationDao_InsertMigrationLog_Call) Run(run func(tx *sqlx.Tx, mLog types.MigrationLog)) *MockMigrationDao_InsertMigrationLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *sqlx.Tx
		if args[0] != nil {
			arg0 = args[0].(*sqlx.Tx)
		}
		var arg1 types.MigrationLog
		if args[1] != nil {
			arg1 = args[1].(types.MigrationLog)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMigrationDao_InsertMigrationLog_Call) Return(err error) *MockMigrationDao_InsertMigrationLog_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMigrationDao_InsertMigrationLog_Call) RunAndReturn(run func(tx *sqlx.Tx, mLog types.MigrationLog) error) *MockMigrationDao_InsertMigrationLog_Call {
	_c.Call.Return(run)
	return _c
}

// SetupMigrationTable provides a mock function for the type MockMigrationDao
func (_mock *MockMigrationDao) SetupMigrationTable(tx *sqlx.Tx) error {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for SetupMigrationTable")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*sqlx.Tx) error); ok {
		r0 = returnFunc(tx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMigrationDao_SetupMigrationTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetupMigrationTable'
type MockMigrationDao_SetupMigrationTable_Call struct {
	*mock.Call
}

// SetupMigrationTable is a helper method to define mock.On call
//   - tx *sqlx.Tx
func (_e *MockMigrationDao_Expecter) SetupMigrationTable(tx interface{}) *MockMigrationDao_SetupMigrationTable_Call {
	return &MockMigrationDao_SetupMigrationTable_Call{Call: _e.mock.On("SetupMigrationTable", tx)}
}

func (_c *MockMigrationDao_SetupMigrationTable_Call) Run(run func(tx *sqlx.Tx)) *MockMigrationDao_SetupMigrationTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *sqlx.Tx
		if args[0] != nil {
			arg0 = args[0].(*sqlx.Tx)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMigrationDao_SetupMigrationTable_Call) Return(err error) *MockMigrationDao_SetupMigrationTable_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMigrationDao_SetupMigrationTable_Call) RunAndReturn(run func(tx *sqlx.Tx) error) *MockMigrationDao_SetupMigrationTable_Call {
	_c.Call.Return(run)
	return _c
}
